image: nginx:mainline-alpine
  volumes:
   - ./mysite.template:/etc/nginx/conf.d/mysite.template
  environment:
   - SERVER_NAMES_REDIRECT=foobar.com
  command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"